### ISSUE TITLE
Reitit doesn't like integrant refs

### ISSUE THREAD

**Issue by yannvanhalewyn** [yannvanhalewyn/duct-reitit#1]
@weavejester The router works, the module not yet. The issue I'm having is that, unlike with ataraxy where you can pass a map of middlewares and handlers to use along side the route definitions, reitit only supports this approach for middleware. This makes it so that I can use `#ig/ref`'s when using the router in the base profile, since they are initialised before the router. But when it comes to the module version we don't have the handlers handy. What would be the correct approach to this?

(I learned duct, integrant and reitit only this weekend, so I might be missing the obvious.)

Another minor issue I'm having is that the router version works but won't use the correct mime type (always returns octet-stream). I'll dig into it but if you have experience with Reitit and know the answer feel free to slide that one in here 😉

**Comment by yannvanhalewyn** [comment]
I could use `(ig/init-key handler-key)` when initialising the module but I'm pretty sure that's frowned upon 😈

**Comment by weavejester** [comment]
Can you explain why you're using a module? If it's just to mimic `duct.module/ataraxy`, that library is going to be deprecated soon.

**Comment by yannvanhalewyn** [comment]
Yes, it was to mimic. I also like the approach, why is it being deprecated?

**Comment by weavejester** [comment]
I don't believe the Ataraxy module does anything that can't be replicated with `prep-key`. Also, the feedback I've had is that the abbreviated keys are very confusing - the longer keys in `duct.router/ataraxy` are more verbose, but clearer in intent.

**Comment by yannvanhalewyn** [comment]
I get that. I actually kind of enjoyed a sprinkle of magic and convention for once. But it took me too a while to understand it fully.
I'll get rid of the module.
So how would you achieve those things using prep key? And, if used without the module, would you use `ig/ref` inline in the routes to declare the handler?

**Comment by weavejester** [comment]
> So how would you achieve those things using prep key?

You can add refs and transform the options map any way you want via `prep-key`. The only thing a module allows you to do beyond that is to affect multiple keys at once, which I don't think is necessary in this case.

For example, the `duct.router/ataraxy` component allows you to write:

```edn
:duct.router/ataraxy
{:routes {[:get "/example"] [:foo.handler/example]}}
```

And `prep-key` automatically fills out the missing handler references:

```edn
:duct.router/ataraxy
{:routes {[:get "/example"] [:foo.handler/example]}
 :handlers {:foo.handler/example #ig/ref :foo.handler/example}}
```

And because `:duct.router/ataraxy` inherits from `:duct/router`, if it's the only router in your configuration, it's automatically chosen as the default router.

**Comment by weavejester** [comment]
I've just taken a look at Reitit, and I'm not sure even `prep-key` is necessary. If we take the routing example in the README:

```clojure
["/api"
 ["/math" {:get {:parameters {:query {:x int?, :y int?}}
                 :responses  {200 {:body {:total pos-int?}}}
                 :handler    (fn [{{{:keys [x y]} :query} :parameters}]
                               {:status 200
                                :body {:total (+ x y)}})}}]]
```

Then the corresponding configuration would probably look like:

```edn
{:duct.router/reitit
 {:routes
  ["/api"
   ["/math" {:get {:parameters {:query {:x int?, :y int?}}
                   :responses  {200 {:body {:total pos-int?}}}
                   :handler    #ig/ref foo.handler/math}}]]}
```

My thought is that because reitit relies a lot on standard functions, we might want to automatically convert symbols into functions when we either prep or initiate it. So the symbol `'int?` is converted into the function `clojure.core/int?`.

So perhaps in the `prep-key` stage you walk the tree and resolve all symbols, assuming that unnamespaced symbols are from `clojure.core`. Then in the `init-key` stage you just pass the options directly to the Reitit functions.

**Comment by yannvanhalewyn** [comment]
@weavejester gotcha, will make the changes. And thanks for the explanation, now prep-key makes a lot more sense to me. Awesome stuff!

So to make sure I fully get the intent: in `duct.router/ataraxy` router you used prep key to add the default handlers and infer missing ones. Is this separation from init-key meant also as an ability for consumer code to overwrite the behavior? Or should that be considered private and all changes should come from above?

Edit: I feel like this depends on the component, and for this use case I don't see why this should be overridden by anyone.

**Comment by yannvanhalewyn** [comment]
> I've just taken a look at Reitit, and I'm not sure even prep-key is necessary. 

And yeah, you could do it all in init if you don't transform the keys to references. So no prep key I guess.

**Comment by weavejester** [comment]
> So to make sure I fully get the intent: in `duct.router/ataraxy` router you used prep key to add the default handlers and infer missing ones. Is this separation from init-key meant also as an ability for consumer code to overwrite the behavior?

It's primarily because `prep-key` is run before refs are resolved, and therefore it can add in new refs, while `init-key` is run after refs are resolved.

There's no technical reason to use `prep-key` unless you're adding or changing refs, but from a stylistic point of view, some things can feel more "prep" than "init". Like resolving symbols, for example - because that's very similar to resolving refs, you might expect it to happen before the init stage, and therefore `prep-key` might be a better fit for it.

**Comment by yannvanhalewyn** [comment]
@weavejester Reitit allows to inject an expand function to expand routes. I'll just try to leverage that.

**Comment by yannvanhalewyn** [comment]
Thanks for the clarification 😉
